image:
  file: Dockerfile

vscode:
  extensions:
    - ms-vscode.csharp@1.21.4:lLV3lBwYKRTJ3QAQjtNMaQ==
    - doggy8088.netcore-extension-pack@0.8.0:TI1cJJqhC+ked6DC6fD/rg==
    - jchannon.csharpextensions@1.3.0:/qyq0PYiY/Kc287KLF4X6w==
    - craigthomas.supersharp@0.1.4:m8YWHqiDaPm1TguBm2/7BQ==
    - doggy8088.netcore-snippets@0.2.4:2sWJIj1FvCnJekBdDobPBg==
    - Leopotam.csharpfixformat@0.0.84:1I+vrErKCOr6I/3ECn6kcA==
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - k--kato.docomment@0.1.8:CNPkp66CComHdjDCWNbiQA==
    - formulahendry.dotnet@0.0.4:BDL7fFzO1JaD/56bYMX4pg==
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==
    - formulahendry.dotnet-test-explorer@0.7.1:aMBBHLwB96Y4mOqZ8ucTKw==
    - jorgeserrano.vscode-csharp-snippets@0.3.1:DRjnkQ2XYPXprrvtxE5t7g==
